# Generated by Django 3.0.8 on 2020-10-24 15:12

from django.db import migrations
from django.conf import settings


def update_site_domain(apps, schema_editor):
    Site = apps.get_model("sites",  "Site")
    s, _ = Site.objects.get_or_create(pk=settings.SITE_ID)
    s.domain = settings.HOST
    s.name = settings.SITE_NAME
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique")
    ]

    operations = [
        migrations.RunPython(update_site_domain)
    ]
