SAF_COMMENT_LEVEL = 'Commentaar'
SAF_COMMENT_COLUMN = 'Commentaar'
SAF_UNALIGNED_LEVEL = 'Hele uiting'
SAF_UTT_LEVEL = 'Utt'
PRE_WORDS_HEADERS = ['ID', 'Level', SAF_UNALIGNED_LEVEL]
POST_WORDS_HEADERS = ['Fases', SAF_COMMENT_LEVEL]
PRIMARY_COLOR = '3f51b5'
SECONDARY_COLOR = 'b5a33f'
