# Generated by Django 3.0a1 on 2019-12-18 12:29

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to=analysis.models.get_file_path)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
