# Generated by Django 3.0a1 on 2019-12-19 10:05

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.Transcript.upload_path),
        ),
    ]
