# Generated by Django 3.0a1 on 2019-12-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_corpus_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='analysis.Corpus'),
        ),
    ]
