# Generated by Django 3.0a1 on 2020-02-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_transcript_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=4)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('subcat', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('altitems', models.CharField(blank=True, max_length=50, null=True)),
                ('implies', models.CharField(blank=True, max_length=50, null=True)),
                ('original', models.BooleanField()),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=500, null=True)),
                ('screening', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='analysis.AssessmentMethod')),
            ],
            options={
                'unique_together': {('method', 'query_id')},
            },
        ),
    ]
