# Generated by Django 3.0a1 on 2020-01-22 12:02

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_transcript_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('content', models.FileField(upload_to=analysis.models.Utterance.upload_path)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='analysis.Transcript')),
            ],
        ),
    ]
