# Generated by Django 3.0a1 on 2020-02-24 14:09

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_tam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmethod',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.AssessmentMethod.upload_path),
        ),
    ]
