# Generated by Django 3.0a1 on 2020-02-26 14:50

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_tam_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='parsed_content',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.Transcript.upload_path_parsed),
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('speaker', models.CharField(max_length=50)),
                ('utt_id', models.IntegerField(blank=True, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='analysis.Transcript')),
            ],
        ),
    ]
