# Generated by Django 3.0a1 on 2020-03-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0005_utterance'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corpora', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
