# Generated by Django 3.0a1 on 2020-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20200309_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utterance',
            old_name='text',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='utterance',
            name='parse_tree',
            field=models.TextField(blank=True),
        ),
    ]
