# Generated by Django 3.0a1 on 2020-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_utterance_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquery',
            name='inform',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
