# Generated by Django 3.0a1 on 2020-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_compounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentquery',
            old_name='phase',
            new_name='fase',
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='process',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='special1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='special2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='query',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
