# Generated by Django 3.0a1 on 2020-05-27 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_tarsp_april'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmethod',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
