# Generated by Django 3.0a1 on 2020-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_assessmentmethod_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='extracted_filename',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
