# Generated by Django 3.0a1 on 2020-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_transcript_extracted_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquery',
            name='screening',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='extracted_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
