# Generated by Django 3.0a1 on 2020-09-16 10:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20200904_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('zc_embeddings', models.BooleanField()),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None)),
            ],
            options={
                'verbose_name_plural': 'method categories',
            },
        ),
        migrations.AddField(
            model_name='assessmentmethod',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='analysis.MethodCategory'),
        ),
    ]
