# Generated by Django 3.0a1 on 2020-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20200916_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmethod',
            unique_together={('category', 'name')},
        ),
    ]
