# Generated by Django 3.0.8 on 2020-11-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20200921_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='default_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpora', to='analysis.AssessmentMethod'),
        ),
    ]
