# Generated by Django 3.0.8 on 2020-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20200921_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='status_nr',
            field=models.PositiveIntegerField(choices=[(0, 'unknown'), (1, 'created'), (2, 'converting'), (3, 'converted'), (4, 'conversion-failed'), (5, 'parsing'), (6, 'parsed'), (7, 'parsing-failed')], default=0),
        ),
    ]
