# Generated by Django 3.0.8 on 2021-01-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_corpus_default_method'),
        ('analysis', '0017_auto_20210128_1107'),
    ]

    operations = [
    ]
