# Generated by Django 3.1.11 on 2021-05-31 09:18

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_merge_20210128_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query_file', models.FileField(upload_to=analysis.models.AnalysisRun.upload_path)),
                ('annotation_file', models.FileField(upload_to=analysis.models.AnalysisRun.upload_path)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.transcript')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
