# Generated by Django 3.0.8 on 2020-11-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_remove_old_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='status_nr',
            new_name='status',
        ),
    ]
