# Generated by Django 3.1.11 on 2021-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_status_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='status',
            field=models.CharField(max_length=50, default='unknown', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='status',
        )

    ]
