# Generated by Django 3.1.11 on 2021-06-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_remove_old_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='status_nr',
            new_name='status',
        ),
    ]
