# Generated by Django 3.1.11 on 2021-06-09 16:29

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_xsid_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('query_file', models.FileField(upload_to=analysis.models.AnalysisRun.upload_path)),
                ('annotation_file', models.FileField(upload_to=analysis.models.AnalysisRun.upload_path)),
                ('is_manual_correction', models.BooleanField(default=False, help_text='this run was generated by parsing a user-uploaded SAF-file')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisruns', to='analysis.assessmentmethod')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisruns', to='analysis.transcript')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
