# Generated by Django 3.1.12 on 2021-08-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_transcript_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='method_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='corpora', to='analysis.methodcategory'),
        ),
    ]
