# Generated by Django 3.1.14 on 2022-02-15 14:53

import os

import analysis.models
from django.core.files.base import File
from django.db import migrations, models


def existing_corrected_files(apps, schema_editor):
    Transcript = apps.get_model('analysis', 'Transcript')
    for transcript in Transcript.objects.all():
        if transcript.parsed_content and not transcript.corrected_content:
            if (transcript.corrections) and ('error' not in transcript.corrections.keys()):
                corrected_filename = os.path.basename(transcript.parsed_content.name).replace('.xml', '_corrected.xml')
                with open(transcript.parsed_content.path, 'rb') as parsed_file_content:
                    transcript.corrected_content.save(corrected_filename, File(parsed_file_content))

                transcript.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_utterance_uttno'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='corrected_content',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.Transcript.upload_path_parsed),
        ),
        migrations.RunPython(existing_corrected_files, migrations.RunPython.noop)
    ]
