# Generated by Django 3.1.14 on 2023-11-01 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_filefield_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assessmentquery',
            name='special1',
        ),
        migrations.RemoveField(
            model_name='assessmentquery',
            name='special2',
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='cat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='filter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='unused1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='unused2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentquery',
            name='variants',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='altitems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='implies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='inform',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='item',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='query',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='screening',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='subcat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
