# Generated by Django 3.1.14 on 2023-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_method_subj_adapt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquery',
            name='literal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
